/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-variant": "#2e3545",
        "on-surface": "#dce2f7",
        "error-container": "#93000a",
        "on-error-container": "#ffdad6",
        "surface-container-low": "#141b2b",
        "secondary-container": "#00a572",
        "secondary-fixed": "#6ffbbe",
        "tertiary-container": "#ca8100",
        "surface-bright": "#323949",
        "tertiary": "#ffb95f",
        "on-surface-variant": "#c2c6d6",
        "on-primary-fixed": "#001a42",
        "surface-tint": "#adc6ff",
        "on-secondary-fixed": "#002113",
        "on-tertiary": "#472a00",
        "primary-container": "#4d8eff",
        "on-secondary": "#003824",
        "tertiary-fixed-dim": "#ffb95f",
        "on-tertiary-container": "#3e2400",
        "on-tertiary-fixed": "#2a1700",
        "primary-fixed": "#d8e2ff",
        "outline": "#8c909f",
        "inverse-on-surface": "#293040",
        "secondary-fixed-dim": "#4edea3",
        "primary": "#adc6ff",
        "outline-variant": "#424754",
        "surface-dim": "#0c1322",
        "primary-fixed-dim": "#adc6ff",
        "surface-container-high": "#232a3a",
        "on-secondary-fixed-variant": "#005236",
        "on-background": "#dce2f7",
        "error": "#ffb4ab",
        "background": "#0c1322",
        "tertiary-fixed": "#ffddb8",
        "on-primary-container": "#00285d",
        "surface-container-lowest": "#070e1d",
        "on-primary-fixed-variant": "#004395",
        "on-tertiary-fixed-variant": "#653e00",
        "inverse-primary": "#005ac2",
        "on-primary": "#002e6a",
        "surface-container": "#191f2f",
        "secondary": "#4edea3",
        "inverse-surface": "#dce2f7",
        "surface-container-highest": "#2e3545",
        "on-error": "#690005",
        "on-secondary-container": "#00311f",
        "surface": "#0c1322"
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem"
      },
      spacing: {
        "container-max": "1440px",
        "base": "4px",
        "sm": "8px",
        "sidebar-width": "260px",
        "xl": "32px",
        "xs": "4px",
        "lg": "24px",
        "sidebar-collapsed": "64px",
        "md": "16px"
      },
      fontFamily: {
        "label-md": ["Inter", "sans-serif"],
        "headline-sm": ["Inter", "sans-serif"],
        "display-lg-mobile": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "code-sm": ["monospace"],
        "headline-md": ["Inter", "sans-serif"],
        "display-lg": ["Inter", "sans-serif"]
      },
      fontSize: {
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
        "headline-sm": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "display-lg-mobile": ["28px", { lineHeight: "34px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "code-sm": ["13px", { lineHeight: "18px", fontWeight: "400" }],
        "headline-md": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "display-lg": ["36px", { lineHeight: "44px", letterSpacing: "-0.02em", fontWeight: "700" }]
      }
    },
  },
  plugins: [],
};